test

diff --git a/.github/workflows/synchronize-ha-files.yaml b/.github/workflows/synchronize-ha-files.yaml
--- a/.github/workflows/synchronize-ha-files.yaml
+++ b/.github/workflows/synchronize-ha-files.yaml
@@ -59,11 +59,18 @@ jobs:
       
       - name: Validate configuration
         run: |
-          curl -X POST -H "Authorization: Bearer ${{ secrets.HASS_TOKEN }}" -H "Content-Type: application/json" $HASS_SERVER }}/api/config/core/check
+          response=$(curl -s -X POST -H "Authorization: Bearer ${{ secrets.HASS_TOKEN }}" -H "Content-Type: application/json" $HASS_SERVER/api/config/core/check_config)
+          echo "Validation Response: $response"
+          if [[ $response == *'"result":"valid"'* ]]; then
+            echo "Configuration is valid, proceeding to reload."
+          else
+            echo "Configuration validation failed, aborting."
+            exit 1
+          fi
       
-      - name: Reload configuration
-        run: |
-          curl -X POST -H "Authorization: Bearer ${{ secrets.HASS_TOKEN }}" -H "Content-Type: application/json" $HASS_SERVER }}/api/services/homeassistant/reload
+      # - name: Reload configuration
+      #   run: |
+      #     curl -X POST -H "Authorization: Bearer ${{ secrets.HASS_TOKEN }}" -H "Content-Type: application/json" $HASS_SERVER }}/api/services/homeassistant/reload
 
 
 # # przełądowanie konfiguracji za pomocą hass-cli
